version: "3"

services:
  atomdance:
    image: atomdance:0.1-unreleased
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: "host"